#pragma once

#define DEVICE_NAME "herc-hotel-p4"
#define MQTT_URI "mqtt://10.1.70.53:1883"
#define MQTT_USER "herc"
#define MQTT_PASS "nemo"

#define MQTT_STATUS_TOPIC DEVICE_NAME "/status"
#define MQTT_HEALTH_TOPIC DEVICE_NAME "/health"
#define MQTT_CMD_OTA_TOPIC DEVICE_NAME "/cmd/ota"
#define MQTT_CMD_REBOOT_TOPIC DEVICE_NAME "/cmd/reboot"
#define MQTT_CMD_LEAK_THRESHOLD_TOPIC DEVICE_NAME "/cmd/leak_threshold"
#define MQTT_CMD_RING_TOPIC DEVICE_NAME "/cmd/ring"
#define MQTT_CMD_RING_DEFAULT_TOPIC DEVICE_NAME "/cmd/ring_default"
#define MQTT_CMD_TELEMETRY_MODE_TOPIC DEVICE_NAME "/cmd/telemetry_mode"
#define MQTT_DEBUG_TOPIC DEVICE_NAME "/debug"
#define MQTT_OTA_STATE_TOPIC DEVICE_NAME "/ota/state"
#define MQTT_RING_STATE_TOPIC DEVICE_NAME "/ring/state"
#define MQTT_RING_DEFAULT_STATE_TOPIC DEVICE_NAME "/ring/default_state"
#define MQTT_TELEMETRY_MODE_TOPIC DEVICE_NAME "/telemetry/mode"
#define MQTT_I2C_SCAN_TOPIC DEVICE_NAME "/i2c/scan"
#define MQTT_I2C_TOPIC_PREFIX DEVICE_NAME "/i2c"
#define MQTT_BME_TOPIC_PREFIX DEVICE_NAME "/bme688"
#define MQTT_BENDER_TOPIC_PREFIX DEVICE_NAME "/bender"
#define MQTT_LEAK_TOPIC_PREFIX DEVICE_NAME "/leak"
#define MQTT_LEAK_THRESHOLD_TOPIC DEVICE_NAME "/leak/threshold"
#define MQTT_MOTOR_TEMP_OFFSET_TOPIC DEVICE_NAME "/i2c/motor_temperature/offset"
#define LEAK_WET_THRESHOLD_V 3.2f

#define ETH_PHY_ADDR 1
#define ETH_PHY_RESET_GPIO 51
#define ETH_MDC_GPIO 31
#define ETH_MDIO_GPIO 52

#define I2C_PORT I2C_NUM_1
#define I2C_SDA_GPIO 4
#define I2C_SCL_GPIO 5

#define BENDER_UART_PORT UART_NUM_1
#define BENDER_UART_TX_GPIO 24
#define BENDER_UART_RX_GPIO 22
#define BENDER_UART_BAUD 115200

#define STATUS_LED_GPIO 25
#define STATUS_LED_GPIO_2 26
#define STATUS_LED_ACTIVE_LOW 1
#define STATUS_LED_BLINK_MS 500

#define NEOPIXEL_ENABLED 1
#define NEOPIXEL_GPIO 3
#define NEOPIXEL_COUNT 18
#define NEOPIXEL_DEFAULT_BRIGHTNESS 255
#define NEOPIXEL_DEFAULT_BLINK_HALF_MS 250
#define NEOPIXEL_COMMAND_TIMEOUT_MS 600000
#define NEOPIXEL_SNAPSHOT_SUPPRESS_MS 600000
#define NEOPIXEL_ALLOW_COLOR_COMMANDS 0
#define NEOPIXEL_RGBW 1
